/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package rpdms;

import java.awt.Dimension;
import java.awt.Font;
import java.awt.GraphicsEnvironment;
import java.awt.event.KeyEvent;
import javax.sound.sampled.AudioInputStream;
import javax.sound.sampled.AudioSystem;
import javax.sound.sampled.Clip;
import javax.swing.JOptionPane;
import javax.swing.plaf.basic.BasicInternalFrameUI;


/**
 *
 * @author 3855-1169
 */
public class Janela_Login extends javax.swing.JInternalFrame {
    
    
    public Janela_Login() {
        
        
        //Remove abas da janela
        BasicInternalFrameUI bi = (BasicInternalFrameUI)this.getUI();
        bi.setNorthPane(null);
        
        initComponents();
    }
    
    //Função para centralizar janela
    public void setPosicao() {
        Dimension d = this.getDesktopPane().getSize();
        this.setLocation((d.width - this.getSize().width) / 2, (d.height - this.getSize().height) / 2);
    }
    
    public void setVisibleLogin(){
        MenuPrincipal.jPanel1.setVisible(true);
        MenuPrincipal.botão_viatura.setVisible(true);
        MenuPrincipal.botão_casos.setVisible(true);
        MenuPrincipal.botão_cctv.setVisible(true);
        MenuPrincipal.botão_perfil.setVisible(true);
    }
    
    public void setVisibleLoginAdmin(){
        MenuPrincipal.botão_docpessoais.setVisible(true);
        MenuPrincipal.botão_relatorios.setVisible(true);
        MenuPrincipal.botão_umbrella.setVisible(true);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        Campo_Nome = new javax.swing.JTextField();
        Campo_Senha = new javax.swing.JPasswordField();
        Nome = new javax.swing.JLabel();
        Senha = new javax.swing.JLabel();
        Botão_Login = new javax.swing.JButton();
        Botão_EsqSenha = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        LOGIN = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(210, 210, 210), new java.awt.Color(210, 210, 210), new java.awt.Color(68, 67, 63), new java.awt.Color(68, 67, 63)));
        setClosable(true);
        setVisible(true);

        jPanel1.setBackground(new java.awt.Color(165, 165, 157));

        jPanel3.setBackground(new java.awt.Color(45, 45, 45));
        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED, new java.awt.Color(210, 210, 210), new java.awt.Color(210, 210, 210), new java.awt.Color(68, 67, 63), new java.awt.Color(68, 67, 63)));

        Campo_Nome.setBackground(new java.awt.Color(240, 240, 240));
        Campo_Nome.setFont(new java.awt.Font("Courier New", 0, 18)); // NOI18N
        Campo_Nome.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        Campo_Nome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Campo_NomeMouseClicked(evt);
            }
        });
        Campo_Nome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Campo_NomeActionPerformed(evt);
            }
        });
        Campo_Nome.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                Campo_NomeKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                Campo_NomeKeyTyped(evt);
            }
        });

        Campo_Senha.setBackground(new java.awt.Color(240, 240, 240));
        Campo_Senha.setFont(new java.awt.Font("Courier New", 0, 18)); // NOI18N
        Campo_Senha.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        Campo_Senha.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Campo_SenhaMouseClicked(evt);
            }
        });
        Campo_Senha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Campo_SenhaActionPerformed(evt);
            }
        });
        Campo_Senha.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                Campo_SenhaKeyTyped(evt);
            }
        });

        Nome.setFont(new java.awt.Font("RE3", 0, 22)); // NOI18N
        Nome.setForeground(new java.awt.Color(240, 240, 240));
        Nome.setText("Nome");

        Senha.setFont(new java.awt.Font("RE3", 0, 22)); // NOI18N
        Senha.setForeground(new java.awt.Color(240, 240, 240));
        Senha.setText("Senha");

        Botão_Login.setFont(new java.awt.Font("RE3", 0, 18)); // NOI18N
        Botão_Login.setText("Login");
        Botão_Login.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Botão_Login.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Botão_LoginMouseClicked(evt);
            }
        });
        Botão_Login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Botão_LoginActionPerformed(evt);
            }
        });

        Botão_EsqSenha.setBackground(new java.awt.Color(45, 45, 45));
        Botão_EsqSenha.setFont(new java.awt.Font("RE3", 0, 16)); // NOI18N
        Botão_EsqSenha.setForeground(new java.awt.Color(240, 240, 240));
        Botão_EsqSenha.setText("Esqueceu sua Senha ?");
        Botão_EsqSenha.setBorder(null);
        Botão_EsqSenha.setContentAreaFilled(false);
        Botão_EsqSenha.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Botão_EsqSenhaMouseClicked(evt);
            }
        });
        Botão_EsqSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Botão_EsqSenhaActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(230, 227, 218));
        jPanel2.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(210, 210, 210), new java.awt.Color(210, 210, 210), new java.awt.Color(68, 67, 63), new java.awt.Color(68, 67, 63)), javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(210, 210, 210), new java.awt.Color(210, 210, 210), new java.awt.Color(68, 67, 63), new java.awt.Color(68, 67, 63))));

        LOGIN.setFont(new java.awt.Font("RE3", 1, 26)); // NOI18N
        LOGIN.setText("LOGIN");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(189, 189, 189)
                .addComponent(LOGIN)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(LOGIN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(5, 5, 5))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Senha)
                    .addComponent(Nome))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Campo_Senha)
                    .addComponent(Campo_Nome, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(98, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(Botão_EsqSenha)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Botão_Login, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Campo_Nome, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Nome, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Campo_Senha, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Senha, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Botão_Login, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Botão_EsqSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(8, 8, 8))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(8, 8, 8))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Botão_EsqSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Botão_EsqSenhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Botão_EsqSenhaActionPerformed

    private void Botão_EsqSenhaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Botão_EsqSenhaMouseClicked
        try {
            AudioInputStream as = AudioSystem.getAudioInputStream(this.getClass().getResource("/Sounds/interfaceSFX/Botão_select.wav"));
            Clip clip = AudioSystem.getClip();
            clip.open(as);
            clip.start( );
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,"Erro");
        }
    }//GEN-LAST:event_Botão_EsqSenhaMouseClicked

    private void Botão_LoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Botão_LoginActionPerformed
        try {
            AudioInputStream as = AudioSystem.getAudioInputStream(this.getClass().getResource("/Sounds/interfaceSFX/Botão_select.wav"));
            Clip clip = AudioSystem.getClip();
            clip.open(as);
            clip.start( );
            
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,"Erro");
        }
        
        String user = Campo_Nome.getText();
        String pass = new String(Campo_Senha.getPassword());
        
        try{
            if(user.equals("Brian Irons") && pass.equals("2236")){
                setVisibleLoginAdmin();
            }
        }catch(Exception e){
            
        }
        
        setVisibleLogin();
        
        dispose();
       
    }//GEN-LAST:event_Botão_LoginActionPerformed

    private void Botão_LoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Botão_LoginMouseClicked
        try {
            AudioInputStream as = AudioSystem.getAudioInputStream(this.getClass().getResource("/Sounds/interfaceSFX/Botão_select.wav"));
            Clip clip = AudioSystem.getClip();
            clip.open(as);
            clip.start( );
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,"Erro");
        }
    }//GEN-LAST:event_Botão_LoginMouseClicked

    private void Campo_SenhaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Campo_SenhaKeyTyped
        if(evt.getKeyChar() == KeyEvent.VK_BACK_SPACE || evt.getKeyChar() == KeyEvent.VK_ENTER){
            try {
                AudioInputStream as = AudioSystem.getAudioInputStream(this.getClass().getResource("/Sounds/interfaceSFX/Digito_backspace.wav"));
                Clip clip = AudioSystem.getClip();
                clip.open(as);
                clip.start( );
            }
            catch(Exception e)
            {
                JOptionPane.showMessageDialog(null,"Erro");
            }
        }else{
            try {
                AudioInputStream as = AudioSystem.getAudioInputStream(this.getClass().getResource("/Sounds/interfaceSFX/Digito.wav"));
                Clip clip = AudioSystem.getClip();
                clip.open(as);
                clip.start( );
            }
            catch(Exception e)
            {
                JOptionPane.showMessageDialog(null,"Erro");
            }
        }
    }//GEN-LAST:event_Campo_SenhaKeyTyped

    private void Campo_SenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Campo_SenhaActionPerformed

    }//GEN-LAST:event_Campo_SenhaActionPerformed

    private void Campo_SenhaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Campo_SenhaMouseClicked
        try {
            AudioInputStream as = AudioSystem.getAudioInputStream(this.getClass().getResource("/Sounds/interfaceSFX/Botão_select.wav"));
            Clip clip = AudioSystem.getClip();
            clip.open(as);
            clip.start( );
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,"Erro");
        }
    }//GEN-LAST:event_Campo_SenhaMouseClicked

        // Adiciona som ao digitar
    private void Campo_NomeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Campo_NomeKeyTyped

        if(evt.getKeyChar() == KeyEvent.VK_BACK_SPACE){
            try {
                AudioInputStream as = AudioSystem.getAudioInputStream(this.getClass().getResource("/Sounds/interfaceSFX/Digito_backspace.wav"));
                Clip clip = AudioSystem.getClip();
                clip.open(as);
                clip.start( );
            }
            catch(Exception e)
            {
                JOptionPane.showMessageDialog(null,"Erro");
            }
        }else{
            try {
                AudioInputStream as = AudioSystem.getAudioInputStream(this.getClass().getResource("/Sounds/interfaceSFX/Digito.wav"));
                Clip clip = AudioSystem.getClip();
                clip.open(as);
                clip.start( );
            }
            catch(Exception e)
            {
                JOptionPane.showMessageDialog(null,"Erro");
            }
        }
    }//GEN-LAST:event_Campo_NomeKeyTyped

    // Adiciona som ao pressionar teclas específicas
    private void Campo_NomeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Campo_NomeKeyPressed

        if(evt.getKeyCode() == KeyEvent.VK_SPACE){
            try {
                AudioInputStream as = AudioSystem.getAudioInputStream(this.getClass().getResource("/Sounds/interfaceSFX/Digito_espaço.wav"));
                Clip clip = AudioSystem.getClip();
                clip.open(as);
                clip.start( );
            }
            catch (Exception e) {
                JOptionPane.showMessageDialog(null,"Erro");
            }

        }
    }//GEN-LAST:event_Campo_NomeKeyPressed

    private void Campo_NomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Campo_NomeActionPerformed
        
    }//GEN-LAST:event_Campo_NomeActionPerformed

    private void Campo_NomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Campo_NomeMouseClicked
        try {
            AudioInputStream as = AudioSystem.getAudioInputStream(this.getClass().getResource("/Sounds/interfaceSFX/Botão_select.wav"));
            Clip clip = AudioSystem.getClip();
            clip.open(as);
            clip.start( );
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,"Erro");
        }
    }//GEN-LAST:event_Campo_NomeMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Botão_EsqSenha;
    private javax.swing.JButton Botão_Login;
    public static javax.swing.JTextField Campo_Nome;
    public static javax.swing.JPasswordField Campo_Senha;
    private javax.swing.JLabel LOGIN;
    private javax.swing.JLabel Nome;
    private javax.swing.JLabel Senha;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}