/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package rpdms;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.GraphicsEnvironment;
import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.concurrent.TimeUnit;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.sound.sampled.AudioInputStream;
import javax.sound.sampled.AudioSystem;
import javax.sound.sampled.Clip;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JInternalFrame;
import javax.swing.JOptionPane;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author 3855-1169
 */
public class Janela_Perfil_STARS extends javax.swing.JInternalFrame {

    
    public Janela_Perfil_STARS() {
        BasicInternalFrameUI bi = (BasicInternalFrameUI)this.getUI();
        bi.setNorthPane(null);
        initComponents();
        
        // deixar visiveis apenas as colunas ID, Nome, Divisão e Patente
        
        escondeColuna(4);
        escondeColuna(5);
        escondeColuna(6);
        escondeColuna(7);
        escondeColuna(8);
        escondeColuna(9);
        escondeColuna(10);
        escondeColuna(11);
        escondeColuna(12);
        escondeColuna(13);
    }

    private static Janela_Perfil_STARS myInstance; // Abre uma mesma janela por vez

    public static Janela_Perfil_STARS getInstance() {
        if (myInstance == null) {
        myInstance = new Janela_Perfil_STARS();
    }
    return myInstance;
   }
    
    public void centralizarJanela(JInternalFrame jif){
        
        Dimension desktopSize = getParent().getSize();
        Dimension jInternalFrameSize = jif.getSize();
            jif.setLocation((desktopSize.width - jInternalFrameSize.width)/2,
            (desktopSize.height- jInternalFrameSize.height)/2);
        jif.setVisible(true);
    }
    
    public void escondeColuna(int indice){
        lista.getColumnModel().getColumn(indice).setMinWidth(0);
        lista.getColumnModel().getColumn(indice).setMaxWidth(0);
        lista.getColumnModel().getColumn(indice).setWidth(0);
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        perfis_de_usuários = new javax.swing.JLabel();
        Botão_X = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        OFICIAIS = new javax.swing.JButton();
        titulo = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lista = new javax.swing.JTable();
        STARS = new javax.swing.JButton();
        adicionar = new javax.swing.JButton();
        editar = new javax.swing.JButton();
        remover = new javax.swing.JButton();

        setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(210, 210, 210), new java.awt.Color(210, 210, 210), new java.awt.Color(68, 67, 63), new java.awt.Color(68, 67, 63)));
        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setPreferredSize(new java.awt.Dimension(800, 600));
        setVisible(false);

        jPanel2.setBackground(new java.awt.Color(172, 169, 162));
        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(210, 210, 210), new java.awt.Color(210, 210, 210), null, null));
        jPanel2.setPreferredSize(new java.awt.Dimension(800, 600));

        jPanel1.setBackground(new java.awt.Color(45, 45, 45));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED, new java.awt.Color(210, 210, 210), new java.awt.Color(210, 210, 210), new java.awt.Color(68, 67, 63), new java.awt.Color(68, 67, 63)));
        jPanel1.setPreferredSize(new java.awt.Dimension(800, 600));
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel1MousePressed(evt);
            }
        });
        jPanel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel1MouseDragged(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(230, 227, 218));
        jPanel3.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(210, 210, 210), new java.awt.Color(210, 210, 210), new java.awt.Color(68, 67, 63), new java.awt.Color(68, 67, 63)), javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(210, 210, 210), new java.awt.Color(210, 210, 210), new java.awt.Color(68, 67, 63), new java.awt.Color(68, 67, 63))));

        perfis_de_usuários.setFont(new java.awt.Font("RE3", 0, 24)); // NOI18N
        perfis_de_usuários.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        perfis_de_usuários.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/icons/icon_perfil_mini.png"))); // NOI18N
        perfis_de_usuários.setText(" Perfis de usuários");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(perfis_de_usuários)
                .addGap(271, 271, 271))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(perfis_de_usuários, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        Botão_X.setBackground(new java.awt.Color(204, 0, 0));
        Botão_X.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Botão_X.setForeground(new java.awt.Color(210, 210, 210));
        Botão_X.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(255, 51, 51), new java.awt.Color(255, 51, 51), new java.awt.Color(153, 0, 0), new java.awt.Color(153, 0, 0)), javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(255, 51, 51), new java.awt.Color(255, 51, 51), new java.awt.Color(153, 0, 0), new java.awt.Color(153, 0, 0))));
        Botão_X.setLabel("X");
        Botão_X.setPreferredSize(new java.awt.Dimension(34, 34));
        Botão_X.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Botão_XActionPerformed(evt);
            }
        });

        jPanel4.setBackground(new java.awt.Color(115, 116, 111));
        jPanel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(155, 155, 155), new java.awt.Color(155, 155, 155), null, null));

        OFICIAIS.setBackground(new java.awt.Color(81, 81, 79));
        OFICIAIS.setFont(new java.awt.Font("RE3", 0, 30)); // NOI18N
        OFICIAIS.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/icons/icon_rpd.png"))); // NOI18N
        OFICIAIS.setText("OFICIAIS");
        OFICIAIS.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        OFICIAIS.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        OFICIAIS.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        OFICIAIS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OFICIAISActionPerformed(evt);
            }
        });

        titulo.setEditable(false);
        titulo.setBackground(new java.awt.Color(188, 189, 184));
        titulo.setFont(new java.awt.Font("RE3", 0, 24)); // NOI18N
        titulo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        titulo.setText("( Special Tactics And Rescue Service )");
        titulo.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED, new java.awt.Color(210, 210, 210), new java.awt.Color(210, 210, 210), null, null));

        jPanel5.setBackground(new java.awt.Color(115, 116, 111));
        jPanel5.setPreferredSize(new java.awt.Dimension(561, 4));

        jScrollPane1.setBackground(new java.awt.Color(115, 116, 111));
        jScrollPane1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED, new java.awt.Color(210, 210, 210), new java.awt.Color(210, 210, 210), null, null));

        lista.setAutoCreateRowSorter(true);
        lista.setFont(new java.awt.Font("RE3", 0, 18)); // NOI18N
        lista.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nome", "Divisão", "Patente", "Data Nascimento", "Sexo", "Raça", "Tipo Sanguineo", "CPF", "Endereço", "Formação", "Especialidades", "Assinatura", "Fotos"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        lista.setRowHeight(30);
        lista.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(lista);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 561, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 4, Short.MAX_VALUE))
        );

        STARS.setFont(new java.awt.Font("RE3", 0, 30)); // NOI18N
        STARS.setForeground(new java.awt.Color(240, 240, 240));
        STARS.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/icons/icon_stars.png"))); // NOI18N
        STARS.setText(" S.T.A.R.S.");
        STARS.setBorder(null);
        STARS.setContentAreaFilled(false);
        STARS.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        STARS.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        adicionar.setFont(new java.awt.Font("RE3", 0, 18)); // NOI18N
        adicionar.setText("Adicionar");
        adicionar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        adicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adicionarActionPerformed(evt);
            }
        });

        editar.setFont(new java.awt.Font("RE3", 0, 18)); // NOI18N
        editar.setText("Editar");
        editar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        editar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        editar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarActionPerformed(evt);
            }
        });

        remover.setFont(new java.awt.Font("RE3", 0, 18)); // NOI18N
        remover.setText("Remover");
        remover.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        remover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(OFICIAIS, javax.swing.GroupLayout.DEFAULT_SIZE, 195, Short.MAX_VALUE)
                    .addComponent(STARS, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(titulo)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(adicionar, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(editar, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(remover, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        jPanel4Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {adicionar, editar, remover});

        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 394, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(adicionar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(editar)
                            .addComponent(remover))
                        .addContainerGap())
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(STARS, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(OFICIAIS, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );

        jPanel4Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {adicionar, editar, remover});

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 746, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(Botão_X, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Botão_X, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 784, Short.MAX_VALUE)
                .addGap(4, 4, 4))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 585, Short.MAX_VALUE)
                .addGap(4, 4, 4))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 796, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 597, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Botão_XActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Botão_XActionPerformed
        
        MenuPrincipal.Iniciar.setEnabled(true);
        MenuPrincipal.botão_umbrella.setEnabled(true);
        
        try {
            AudioInputStream as = AudioSystem.getAudioInputStream(this.getClass().getResource("/Sounds/InterfaceSFX/Botão_sair.wav"));
            Clip clip = AudioSystem.getClip();
            clip.open(as);
            clip.start( );
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,"Erro");
        };
        
        try {
            TimeUnit.MILLISECONDS.sleep(100);
        } catch (InterruptedException ex) {
            Logger.getLogger(Janela_Sobre.class.getName()).log(Level.SEVERE, null, ex);
        }
        dispose();
        this.getDesktopPane().remove(this);
    }//GEN-LAST:event_Botão_XActionPerformed

    private void OFICIAISActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OFICIAISActionPerformed
        Janela_Perfil_RPD perfil2 = Janela_Perfil_RPD.getInstance();
        
        perfil2.pack();
        
        if (perfil2.isVisible()){
            
        } else {
            getParent().add(perfil2);
            perfil2.setVisible(true);
        }
        
        String user = Janela_Login.Campo_Nome.getText();
        String pass = new String(Janela_Login.Campo_Senha.getPassword());
        
        if(user.equals("Brian Irons") && pass.equals("2236")){
            
           Janela_Perfil_RPD.adicionar.setVisible(true);
           Janela_Perfil_RPD.editar.setVisible(true);
           Janela_Perfil_RPD.remover.setVisible(true);
        }else{
           Janela_Perfil_RPD.adicionar.setVisible(false);
           Janela_Perfil_RPD.editar.setVisible(false);
           Janela_Perfil_RPD.remover.setVisible(false); 
        }
        
        try {
            AudioInputStream as = AudioSystem.getAudioInputStream(this.getClass().getResource("/Sounds/interfaceSFX/Botão_select.wav"));
            Clip clip = AudioSystem.getClip();
            clip.open(as);
            clip.start( );
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,"Erro");
        }
        
        centralizarJanela(perfil2);
        
        dispose();
        this.getDesktopPane().remove(this);
    }//GEN-LAST:event_OFICIAISActionPerformed
    
 // Permite movimentar a tela 
    
    int posx,posy;
    private void jPanel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MousePressed
        posx = evt.getX();
        posy = evt.getY();
    }//GEN-LAST:event_jPanel1MousePressed

    private void jPanel1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseDragged
        this.setLocation(this.getX() + evt.getX() - posx, this.getY() + evt.getY() - posy);
    }//GEN-LAST:event_jPanel1MouseDragged

    private void adicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adicionarActionPerformed
        final DefaultTableModel modelo = (DefaultTableModel)lista.getModel();
        
        try {
            AudioInputStream as = AudioSystem.getAudioInputStream(this.getClass().getResource("/Sounds/interfaceSFX/Botão_select.wav"));
            Clip clip = AudioSystem.getClip();
            clip.open(as);
            clip.start( );
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,"Erro");
        }
        
        final Perfil perfil = Perfil.getInstance();
        perfil.setVisible(true);
        
        perfil.text_ID.setEditable(true);
        perfil.text_cpf.setEditable(true);
        perfil.text_datanasc.setEditable(true);
        perfil.text_divisão.setEditable(true);
        perfil.text_endereço.setEditable(true);
        perfil.text_especialidades.setEditable(true);
        perfil.text_formação.setEditable(true);
        perfil.text_nome.setEditable(true);
        perfil.text_patente.setEditable(true);
        perfil.text_raça.setEditable(true);
        perfil.text_sexo.setEditable(true);
        perfil.text_ts.setEditable(true);
        
        final Object[] linha = new Object[14];
        
        perfil.Salvar.addActionListener(new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent ae) {
                
                try {
                    AudioInputStream as = AudioSystem.getAudioInputStream(this.getClass().getResource("/Sounds/interfaceSFX/Botão_select.wav"));
                    Clip clip = AudioSystem.getClip();
                    clip.open(as);
                    clip.start( );
                }
                catch(Exception e)
                {
                    JOptionPane.showMessageDialog(null,"Erro");
                }
                
                linha[0] = perfil.text_ID.getText();
                linha[1] = perfil.text_nome.getText();
                linha[2] = perfil.text_divisão.getText();
                linha[3] = perfil.text_patente.getText();
                linha[4] = perfil.text_datanasc.getText();
                linha[5] = perfil.text_sexo.getText();
                linha[6] = perfil.text_raça.getText();
                linha[7] = perfil.text_ts.getText();
                linha[8] = perfil.text_cpf.getText();
                linha[9] = perfil.text_endereço.getText();
                linha[10] = perfil.text_formação.getText();
                linha[11] = perfil.text_especialidades.getText();
                linha[12] = perfil.text_assinatura.getText();
                linha[13] = perfil.Foto.getIcon();
                modelo.addRow(linha);
                perfil.dispose();
            }
        });
    }//GEN-LAST:event_adicionarActionPerformed

    private void removerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removerActionPerformed
        DefaultTableModel modelo = (DefaultTableModel)lista.getModel();
        int remove_linha = lista.getSelectedRow();
        
        try {
            AudioInputStream as = AudioSystem.getAudioInputStream(this.getClass().getResource("/Sounds/interfaceSFX/Botão_select.wav"));
            Clip clip = AudioSystem.getClip();
            clip.open(as);
            clip.start( );
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,"Erro");
        }
        
        modelo.removeRow(remove_linha);
        
    }//GEN-LAST:event_removerActionPerformed

    private void listaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listaMouseClicked
        int index = lista.getSelectedRow();
        int image = lista.getSelectedRow();
        
        TableModel modelo = lista.getModel();
        
        if(evt.getClickCount()==2){
            
            try {
                AudioInputStream as = AudioSystem.getAudioInputStream(this.getClass().getResource("/Sounds/interfaceSFX/lista_folha.wav"));
                Clip clip = AudioSystem.getClip();
                clip.open(as);
                clip.start( );
            }
            catch(Exception e)
            {
                JOptionPane.showMessageDialog(null,"Erro");
            }
            
            String id = modelo.getValueAt(index, 0).toString();
            String nome = modelo.getValueAt(index, 1).toString();
            String divisao = modelo.getValueAt(index, 2).toString();
            String patente = modelo.getValueAt(index, 3).toString();
            String datanasc = modelo.getValueAt(index, 4).toString();
            String sexo = modelo.getValueAt(index, 5).toString();
            String raça = modelo.getValueAt(index, 6).toString();
            String ts = modelo.getValueAt(index, 7).toString();
            String cpf = modelo.getValueAt(index, 8).toString();
            String endereço = modelo.getValueAt(index, 9).toString();
            String formação = modelo.getValueAt(index, 10).toString();
            String especialidades = modelo.getValueAt(index, 11).toString();
            String assinatura = modelo.getValueAt(index, 12).toString(); 
            
            
        
            Perfil perfil = Perfil.getInstance();
            perfil.Salvar.setVisible(false);
            perfil.Editar.setVisible(false);
            perfil.setVisible(true);
            perfil.pack();
            perfil.setLocationRelativeTo(null);
            perfil.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        
            perfil.text_ID.setText(id);
            perfil.text_nome.setText(nome);
            perfil.text_divisão.setText(divisao);
            perfil.text_patente.setText(patente);
            perfil.text_datanasc.setText(datanasc);
            perfil.text_sexo.setText(sexo);
            perfil.text_raça.setText(raça);
            perfil.text_ts.setText(ts);
            perfil.text_cpf.setText(cpf);
            perfil.text_endereço.setText(endereço);
            perfil.text_formação.setText(formação);
            perfil.text_especialidades.setText(especialidades);
            perfil.text_assinatura.setText(nome);
            
            if(lista.getValueAt(image, 13)!=null){
                ImageIcon img = (ImageIcon)lista.getValueAt(image, 13);
                Image img2 = img.getImage().getScaledInstance(perfil.Foto.getWidth(), perfil.Foto.getHeight(), Image.SCALE_SMOOTH);
                ImageIcon img3 =new ImageIcon (img2);
                perfil.Foto.setIcon(img3);
            }
        }
    }//GEN-LAST:event_listaMouseClicked

    private void editarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarActionPerformed
        int index = lista.getSelectedRow();
        int image = lista.getSelectedRow();
        final TableModel modelo = lista.getModel();
        
        try {
            AudioInputStream as = AudioSystem.getAudioInputStream(this.getClass().getResource("/Sounds/interfaceSFX/Botão_select.wav"));
            Clip clip = AudioSystem.getClip();
            clip.open(as);
            clip.start( );
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,"Erro");
        }
        
        
        String id = modelo.getValueAt(index, 0).toString();
        String nome = modelo.getValueAt(index, 1).toString();
        String divisao = modelo.getValueAt(index, 2).toString();
        String patente = modelo.getValueAt(index, 3).toString();
        String datanasc = modelo.getValueAt(index, 4).toString();
        String sexo = modelo.getValueAt(index, 5).toString();
        String raça = modelo.getValueAt(index, 6).toString();
        String ts = modelo.getValueAt(index, 7).toString();
        String cpf = modelo.getValueAt(index, 8).toString();
        String endereço = modelo.getValueAt(index, 9).toString();
        String formação = modelo.getValueAt(index, 10).toString();
        String especialidades = modelo.getValueAt(index, 11).toString();
        String assinatura = modelo.getValueAt(index, 12).toString();
        
        final Perfil perfil = Perfil.getInstance();
        perfil.Salvar.setVisible(true);
        perfil.setVisible(true);
        perfil.pack();
        perfil.setLocationRelativeTo(null);
        perfil.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        
        perfil.text_ID.setEditable(true);
        perfil.text_cpf.setEditable(true);
        perfil.text_datanasc.setEditable(true);
        perfil.text_divisão.setEditable(true);
        perfil.text_endereço.setEditable(true);
        perfil.text_especialidades.setEditable(true);
        perfil.text_formação.setEditable(true);
        perfil.text_nome.setEditable(true);
        perfil.text_patente.setEditable(true);
        perfil.text_raça.setEditable(true);
        perfil.text_sexo.setEditable(true);
        perfil.text_ts.setEditable(true);
        
        perfil.text_ID.setText(id);
        perfil.text_nome.setText(nome);
        perfil.text_divisão.setText(divisao);
        perfil.text_patente.setText(patente);
        perfil.text_datanasc.setText(datanasc);
        perfil.text_sexo.setText(sexo);
        perfil.text_raça.setText(raça);
        perfil.text_ts.setText(ts);
        perfil.text_cpf.setText(cpf);
        perfil.text_endereço.setText(endereço);
        perfil.text_formação.setText(formação);
        perfil.text_especialidades.setText(especialidades);
        perfil.text_assinatura.setText(nome);
        
        if(lista.getValueAt(image, 13)!=null){
                ImageIcon img = (ImageIcon)lista.getValueAt(image, 13);
                Image img2 = img.getImage().getScaledInstance(perfil.Foto.getWidth(), perfil.Foto.getHeight(), Image.SCALE_SMOOTH);
                ImageIcon img3 =new ImageIcon (img2);
                perfil.Foto.setIcon(img3);
            }
        
        perfil.Salvar.addActionListener(new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent ae) {
                
                try {
                    AudioInputStream as = AudioSystem.getAudioInputStream(this.getClass().getResource("/Sounds/interfaceSFX/Botão_select.wav"));
                    Clip clip = AudioSystem.getClip();
                    clip.open(as);
                    clip.start( );
                }
                catch(Exception e)
                {
                    JOptionPane.showMessageDialog(null,"Erro");
                }
                
                int i = lista.getSelectedRow();
                
                modelo.setValueAt(perfil.text_ID.getText(), i, 0);
                modelo.setValueAt(perfil.text_nome.getText(), i, 1);
                modelo.setValueAt(perfil.text_divisão.getText(), i, 2);
                modelo.setValueAt(perfil.text_patente.getText(), i, 3);
                modelo.setValueAt(perfil.text_datanasc.getText(), i, 4);
                modelo.setValueAt(perfil.text_sexo.getText(), i, 5);
                modelo.setValueAt(perfil.text_raça.getText(), i, 6);
                modelo.setValueAt(perfil.text_ts.getText(), i, 7);
                modelo.setValueAt(perfil.text_cpf.getText(), i, 8);
                modelo.setValueAt(perfil.text_endereço.getText(), i, 9);
                modelo.setValueAt(perfil.text_formação.getText(), i, 10);
                modelo.setValueAt(perfil.text_especialidades.getText(), i, 11);
                modelo.setValueAt(perfil.text_assinatura.getText(), i, 12);
                modelo.setValueAt(perfil.Foto.getIcon(), i, 13);
                perfil.dispose();
            }
        });
    }//GEN-LAST:event_editarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Botão_X;
    private javax.swing.JButton OFICIAIS;
    private javax.swing.JButton STARS;
    public static javax.swing.JButton adicionar;
    public static javax.swing.JButton editar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable lista;
    private javax.swing.JLabel perfis_de_usuários;
    public static javax.swing.JButton remover;
    private javax.swing.JTextField titulo;
    // End of variables declaration//GEN-END:variables
}
