/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package rpdms;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.concurrent.TimeUnit;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.sound.sampled.AudioInputStream;
import javax.sound.sampled.AudioSystem;
import javax.sound.sampled.Clip;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import javax.swing.plaf.basic.BasicInternalFrameUI;

/**
 *
 * @author 3855-1169
 */
public class Janela_CCTV extends javax.swing.JInternalFrame {

    /**
     * Creates new form Janela_CCTV
     */
    public Janela_CCTV() {
        BasicInternalFrameUI bi = (BasicInternalFrameUI)this.getUI();
        bi.setNorthPane(null);
        initComponents();
        showTime();
        showDate();
        tocarMusica();
    }
    
    private static Janela_CCTV myInstance; // Abre uma mesma janela por vez
    
    public static Janela_CCTV getInstance() {
        if (myInstance == null) {
            myInstance = new Janela_CCTV();
    }else{
            myInstance.clip.close();
            myInstance.dispose();
            myInstance = new Janela_CCTV();
        }
    return myInstance;
   }
    
    void showTime(){    //Mostra o horário atual
        new Timer(0, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent ae) {
                Date d= new Date();
                SimpleDateFormat s= new SimpleDateFormat("hh:mm:ss a");
                tempo_1.setText(s.format(d));
                tempo_2.setText(s.format(d));
                tempo_3.setText(s.format(d));
                tempo_4.setText(s.format(d));
            }
        }
        ).start();
     }
    
    void showDate(){    // mostra o dia específico
        Date d= new Date();
        SimpleDateFormat s= new SimpleDateFormat("28-09-1998"); //dia específico
        data_1.setText(s.format(d));
        data_2.setText(s.format(d));
        data_3.setText(s.format(d));
        data_4.setText(s.format(d));
    }

    Clip clip;
    //Função para tocar música na tela
    public void tocarMusica(){
        
        try {
            AudioInputStream as = AudioSystem.getAudioInputStream(this.getClass().getResource("/Sounds/Telas/RPD_creepy.wav"));
            clip = AudioSystem.getClip();
            clip.open(as);
            clip.loop(Clip.LOOP_CONTINUOUSLY);
            clip.start( );
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,"Erro");
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Botão_X = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        Sobre = new javax.swing.JLabel();
        nome1 = new javax.swing.JLabel();
        nome2 = new javax.swing.JLabel();
        nome3 = new javax.swing.JLabel();
        nome4 = new javax.swing.JLabel();
        tempo_1 = new javax.swing.JLabel();
        tempo_2 = new javax.swing.JLabel();
        tempo_3 = new javax.swing.JLabel();
        tempo_4 = new javax.swing.JLabel();
        data_1 = new javax.swing.JLabel();
        data_2 = new javax.swing.JLabel();
        data_3 = new javax.swing.JLabel();
        data_4 = new javax.swing.JLabel();
        camera1 = new javax.swing.JLabel();
        camera2 = new javax.swing.JLabel();
        camera3 = new javax.swing.JLabel();
        camera4 = new javax.swing.JLabel();
        background = new javax.swing.JLabel();

        setBackground(new java.awt.Color(165, 165, 157));
        setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(240, 240, 240), new java.awt.Color(240, 240, 240), null, null), javax.swing.BorderFactory.createLineBorder(new java.awt.Color(165, 165, 157), 4)));
        setIconifiable(true);
        setMaximizable(true);
        setMinimumSize(new java.awt.Dimension(712, 594));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Botão_X.setBackground(new java.awt.Color(204, 0, 0));
        Botão_X.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Botão_X.setForeground(new java.awt.Color(210, 210, 210));
        Botão_X.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(255, 51, 51), new java.awt.Color(255, 51, 51), new java.awt.Color(153, 0, 0), new java.awt.Color(153, 0, 0)), javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(255, 51, 51), new java.awt.Color(255, 51, 51), new java.awt.Color(153, 0, 0), new java.awt.Color(153, 0, 0))));
        Botão_X.setLabel("X");
        Botão_X.setPreferredSize(new java.awt.Dimension(34, 34));
        getContentPane().add(Botão_X, new org.netbeans.lib.awtextra.AbsoluteConstraints(662, 0, -1, -1));

        jPanel2.setBackground(new java.awt.Color(230, 227, 218));
        jPanel2.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(210, 210, 210), new java.awt.Color(210, 210, 210), new java.awt.Color(68, 67, 63), new java.awt.Color(68, 67, 63)), javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(210, 210, 210), new java.awt.Color(210, 210, 210), new java.awt.Color(67, 68, 63), new java.awt.Color(68, 67, 63))));
        jPanel2.setPreferredSize(new java.awt.Dimension(622, 30));
        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel2MousePressed(evt);
            }
        });
        jPanel2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel2MouseDragged(evt);
            }
        });

        Sobre.setFont(new java.awt.Font("RE3", 0, 24)); // NOI18N
        Sobre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Sobre.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/icons/icon_cctv_mini.png"))); // NOI18N
        Sobre.setText("  Sistema CCTV");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(239, Short.MAX_VALUE)
                .addComponent(Sobre)
                .addContainerGap(240, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Sobre, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 662, 34));

        nome1.setFont(new java.awt.Font("RE3", 0, 16)); // NOI18N
        nome1.setForeground(new java.awt.Color(240, 240, 240));
        nome1.setText("Corredor Leste");
        getContentPane().add(nome1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 266, 120, 22));

        nome2.setFont(new java.awt.Font("RE3", 0, 16)); // NOI18N
        nome2.setForeground(new java.awt.Color(240, 240, 240));
        nome2.setText("Entrada Principal");
        getContentPane().add(nome2, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 266, 120, 22));

        nome3.setFont(new java.awt.Font("RE3", 0, 16)); // NOI18N
        nome3.setForeground(new java.awt.Color(240, 240, 240));
        nome3.setText("Corredor S.T.A.R.S.");
        getContentPane().add(nome3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 527, 120, 22));

        nome4.setFont(new java.awt.Font("RE3", 0, 16)); // NOI18N
        nome4.setForeground(new java.awt.Color(240, 240, 240));
        nome4.setText("Escritórios 1F");
        getContentPane().add(nome4, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 527, 120, 22));

        tempo_1.setFont(new java.awt.Font("RE3", 0, 16)); // NOI18N
        tempo_1.setForeground(new java.awt.Color(240, 240, 240));
        tempo_1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(tempo_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(183, 266, 80, 22));

        tempo_2.setFont(new java.awt.Font("RE3", 0, 16)); // NOI18N
        tempo_2.setForeground(new java.awt.Color(240, 240, 240));
        tempo_2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(tempo_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 266, 80, 22));

        tempo_3.setFont(new java.awt.Font("RE3", 0, 16)); // NOI18N
        tempo_3.setForeground(new java.awt.Color(240, 240, 240));
        getContentPane().add(tempo_3, new org.netbeans.lib.awtextra.AbsoluteConstraints(183, 527, 80, 22));

        tempo_4.setFont(new java.awt.Font("RE3", 0, 16)); // NOI18N
        tempo_4.setForeground(new java.awt.Color(240, 240, 240));
        tempo_4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(tempo_4, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 527, 80, 22));

        data_1.setFont(new java.awt.Font("RE3", 0, 16)); // NOI18N
        data_1.setForeground(new java.awt.Color(240, 240, 240));
        data_1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        data_1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(data_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(265, 266, 80, 22));

        data_2.setFont(new java.awt.Font("RE3", 0, 16)); // NOI18N
        data_2.setForeground(new java.awt.Color(240, 240, 240));
        data_2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(data_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(612, 266, 80, 22));

        data_3.setFont(new java.awt.Font("RE3", 0, 16)); // NOI18N
        data_3.setForeground(new java.awt.Color(240, 240, 240));
        getContentPane().add(data_3, new org.netbeans.lib.awtextra.AbsoluteConstraints(265, 527, 80, 22));

        data_4.setFont(new java.awt.Font("RE3", 0, 16)); // NOI18N
        data_4.setForeground(new java.awt.Color(240, 240, 240));
        data_4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(data_4, new org.netbeans.lib.awtextra.AbsoluteConstraints(612, 527, 80, 22));

        camera1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        camera1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/camera1.gif"))); // NOI18N
        getContentPane().add(camera1, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 39, -1, -1));

        camera2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/camera2.gif"))); // NOI18N
        getContentPane().add(camera2, new org.netbeans.lib.awtextra.AbsoluteConstraints(352, 39, -1, -1));

        camera3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/camera3.gif"))); // NOI18N
        getContentPane().add(camera3, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 301, -1, -1));

        camera4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/camera4.gif"))); // NOI18N
        getContentPane().add(camera4, new org.netbeans.lib.awtextra.AbsoluteConstraints(352, 301, -1, -1));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/camera_background.png"))); // NOI18N
        background.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                backgroundMousePressed(evt);
            }
        });
        background.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                backgroundMouseDragged(evt);
            }
        });
        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 34, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents
int posx,posy;
    private void jPanel2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MousePressed
        posx = evt.getX();
        posy = evt.getY();
    }//GEN-LAST:event_jPanel2MousePressed

    private void jPanel2MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseDragged
        this.setLocation(this.getX() + evt.getX() - posx, this.getY() + evt.getY() - posy);
    }//GEN-LAST:event_jPanel2MouseDragged

    private void backgroundMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backgroundMousePressed
        posx = evt.getX();
        posy = evt.getY();
    }//GEN-LAST:event_backgroundMousePressed

    private void backgroundMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backgroundMouseDragged
        this.setLocation(this.getX() + evt.getX() - posx, this.getY() + evt.getY() - posy);
    }//GEN-LAST:event_backgroundMouseDragged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JButton Botão_X;
    private javax.swing.JLabel Sobre;
    private javax.swing.JLabel background;
    private javax.swing.JLabel camera1;
    private javax.swing.JLabel camera2;
    private javax.swing.JLabel camera3;
    private javax.swing.JLabel camera4;
    private javax.swing.JLabel data_1;
    private javax.swing.JLabel data_2;
    private javax.swing.JLabel data_3;
    private javax.swing.JLabel data_4;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel nome1;
    private javax.swing.JLabel nome2;
    private javax.swing.JLabel nome3;
    private javax.swing.JLabel nome4;
    private javax.swing.JLabel tempo_1;
    private javax.swing.JLabel tempo_2;
    private javax.swing.JLabel tempo_3;
    private javax.swing.JLabel tempo_4;
    // End of variables declaration//GEN-END:variables
}
