/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package rpdms;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.concurrent.TimeUnit;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.sound.sampled.AudioInputStream;
import javax.sound.sampled.AudioSystem;
import javax.sound.sampled.Clip;
import javax.swing.JFrame;
import javax.swing.JInternalFrame;
import javax.swing.JOptionPane;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author 3855-1169
 */
public class Janela_Viatura extends javax.swing.JInternalFrame {

    
    int t_cont=0;
    int u_cont=0;
    int d_cont=0;
    int t_cont2=0;
    int u_cont2=0;
    int d_cont2=0;
    
    public Janela_Viatura() {
        BasicInternalFrameUI bi = (BasicInternalFrameUI)this.getUI();
        bi.setNorthPane(null);
        initComponents();
        
        lista_viaturas.setRowHeight(30);
    }
    
    private static Janela_Viatura myInstance; // Abre uma mesma janela por vez

    public static Janela_Viatura getInstance() {
        if (myInstance == null) {
        myInstance = new Janela_Viatura();
    }
    return myInstance;
   }
    
    public void centralizarJanela(JInternalFrame jif){
        
        Dimension desktopSize = getParent().getSize();
        Dimension jInternalFrameSize = jif.getSize();
            jif.setLocation((desktopSize.width - jInternalFrameSize.width)/2,
            (desktopSize.height- jInternalFrameSize.height)/2);
        jif.setVisible(true);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        Sobre = new javax.swing.JLabel();
        Botão_X = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        lista_viaturas = new javax.swing.JTable();
        adicionar = new javax.swing.JButton();
        remover = new javax.swing.JButton();
        editar = new javax.swing.JButton();
        botão_car = new javax.swing.JButton();
        VIATURAS = new javax.swing.JLabel();
        solicitar = new javax.swing.JButton();
        botão_van = new javax.swing.JButton();

        setBackground(new java.awt.Color(165, 165, 157));
        setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(210, 210, 210), new java.awt.Color(210, 210, 210), null, null));
        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);

        jPanel1.setBackground(new java.awt.Color(115, 116, 111));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(68, 67, 63), new java.awt.Color(68, 67, 63), new java.awt.Color(210, 210, 210), new java.awt.Color(210, 210, 210)));
        jPanel1.setPreferredSize(new java.awt.Dimension(776, 500));
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel1MousePressed(evt);
            }
        });
        jPanel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel1MouseDragged(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(230, 227, 218));
        jPanel2.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(210, 210, 210), new java.awt.Color(210, 210, 210), new java.awt.Color(68, 67, 63), new java.awt.Color(68, 67, 63)), javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(210, 210, 210), new java.awt.Color(210, 210, 210), new java.awt.Color(67, 68, 63), new java.awt.Color(68, 67, 63))));
        jPanel2.setPreferredSize(new java.awt.Dimension(622, 30));
        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel2MousePressed(evt);
            }
        });
        jPanel2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel2MouseDragged(evt);
            }
        });

        Sobre.setFont(new java.awt.Font("RE3", 0, 24)); // NOI18N
        Sobre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Sobre.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/icons/icon_viatura_mini.png"))); // NOI18N
        Sobre.setText(" Viaturas");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Sobre)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Sobre, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        Botão_X.setBackground(new java.awt.Color(204, 0, 0));
        Botão_X.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Botão_X.setForeground(new java.awt.Color(210, 210, 210));
        Botão_X.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(255, 51, 51), new java.awt.Color(255, 51, 51), new java.awt.Color(153, 0, 0), new java.awt.Color(153, 0, 0)), javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(255, 51, 51), new java.awt.Color(255, 51, 51), new java.awt.Color(153, 0, 0), new java.awt.Color(153, 0, 0))));
        Botão_X.setLabel("X");
        Botão_X.setPreferredSize(new java.awt.Dimension(34, 34));
        Botão_X.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Botão_XActionPerformed(evt);
            }
        });

        lista_viaturas.setAutoCreateRowSorter(true);
        lista_viaturas.setFont(new java.awt.Font("RE3", 0, 18)); // NOI18N
        lista_viaturas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Modelo", "Placa", "Ano", "Prioridade", "Condição"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        lista_viaturas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lista_viaturasMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(lista_viaturas);
        if (lista_viaturas.getColumnModel().getColumnCount() > 0) {
            lista_viaturas.getColumnModel().getColumn(1).setPreferredWidth(300);
        }

        adicionar.setFont(new java.awt.Font("RE3", 0, 18)); // NOI18N
        adicionar.setText("Adicionar");
        adicionar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        adicionar.setPreferredSize(new java.awt.Dimension(98, 34));
        adicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adicionarActionPerformed(evt);
            }
        });

        remover.setFont(new java.awt.Font("RE3", 0, 18)); // NOI18N
        remover.setText("Remover");
        remover.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        remover.setPreferredSize(new java.awt.Dimension(98, 34));
        remover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removerActionPerformed(evt);
            }
        });

        editar.setFont(new java.awt.Font("RE3", 0, 18)); // NOI18N
        editar.setText("Editar");
        editar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        editar.setPreferredSize(new java.awt.Dimension(98, 34));
        editar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarActionPerformed(evt);
            }
        });

        botão_car.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/icons/viatura_carro.png"))); // NOI18N
        botão_car.setBorder(null);
        botão_car.setOpaque(false);
        botão_car.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        botão_car.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        VIATURAS.setFont(new java.awt.Font("RE3", 0, 24)); // NOI18N
        VIATURAS.setForeground(new java.awt.Color(240, 240, 240));
        VIATURAS.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        VIATURAS.setText("VIATURAS");
        VIATURAS.setPreferredSize(new java.awt.Dimension(100, 34));

        solicitar.setFont(new java.awt.Font("RE3", 0, 18)); // NOI18N
        solicitar.setText("Solicitar");
        solicitar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        solicitar.setPreferredSize(new java.awt.Dimension(98, 34));
        solicitar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                solicitarActionPerformed(evt);
            }
        });

        botão_van.setBackground(new java.awt.Color(81, 81, 79));
        botão_van.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/icons/viatura_van.png"))); // NOI18N
        botão_van.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        botão_van.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        botão_van.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        botão_van.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botão_vanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 738, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(Botão_X, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(adicionar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(solicitar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 108, Short.MAX_VALUE)
                .addComponent(VIATURAS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 108, Short.MAX_VALUE)
                .addComponent(editar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(remover, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(botão_car, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botão_van, javax.swing.GroupLayout.PREFERRED_SIZE, 389, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Botão_X, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE))
                .addGap(0, 0, 0)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(botão_van, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(botão_car, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(adicionar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(remover, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(editar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(VIATURAS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(solicitar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(4, 4, 4))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 505, Short.MAX_VALUE)
                .addGap(4, 4, 4))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Botão_XActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Botão_XActionPerformed

        MenuPrincipal.botão_umbrella.setEnabled(true);
        MenuPrincipal.Iniciar.setEnabled(true);
        
        try {
            AudioInputStream as = AudioSystem.getAudioInputStream(this.getClass().getResource("/Sounds/InterfaceSFX/Botão_sair.wav"));
            Clip clip = AudioSystem.getClip();
            clip.open(as);
            clip.start( );
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,"Erro");
        };
        
        try {
            TimeUnit.MILLISECONDS.sleep(100);
        } catch (InterruptedException ex) {
            Logger.getLogger(Janela_Viatura.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        dispose();
        this.getDesktopPane().remove(this);
        
    }//GEN-LAST:event_Botão_XActionPerformed
            
//Permite movimentar tela
    
    int posx,posy;
    private void jPanel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MousePressed
        posx = evt.getX();
        posy = evt.getY();
    }//GEN-LAST:event_jPanel1MousePressed

    private void jPanel1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseDragged
        this.setLocation(this.getX() + evt.getX() - posx, this.getY() + evt.getY() - posy);
    }//GEN-LAST:event_jPanel1MouseDragged

    private void jPanel2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MousePressed
        posx = evt.getX();
        posy = evt.getY();
    }//GEN-LAST:event_jPanel2MousePressed

    private void jPanel2MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseDragged
        this.setLocation(this.getX() + evt.getX() - posx, this.getY() + evt.getY() - posy);
    }//GEN-LAST:event_jPanel2MouseDragged

    private void adicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adicionarActionPerformed
        final DefaultTableModel modelo = (DefaultTableModel)lista_viaturas.getModel();
        
        try {
            AudioInputStream as = AudioSystem.getAudioInputStream(this.getClass().getResource("/Sounds/interfaceSFX/Botão_select.wav"));
            Clip clip = AudioSystem.getClip();
            clip.open(as);
            clip.start( );
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,"Erro");
        }
        
        final Viatura viatura = Viatura.getInstance();
        getParent().add(viatura);
        viatura.setVisible(true);
        
        viatura.text_ID.setEditable(true);
        viatura.text_modelo.setEditable(true);
        viatura.text_placa.setEditable(true);
        viatura.text_ano.setEditable(true);
        viatura.text_prio.setEditable(true);
        viatura.text_condição.setEditable(true);
        
        centralizarJanela(viatura);
        
        final Object linha[] = new Object[6];

        viatura.Salvar.addActionListener(new ActionListener() {

            
            public void actionPerformed(ActionEvent ae) {
                    try {
                        AudioInputStream as = AudioSystem.getAudioInputStream(this.getClass().getResource("/Sounds/interfaceSFX/Botão_select.wav"));
                        Clip clip = AudioSystem.getClip();
                        clip.open(as);
                        clip.start( );
                    }
                    catch(Exception e)
                    {
                        JOptionPane.showMessageDialog(null,"Erro");
                    }
                    
                    
                    linha[0]=viatura.text_ID.getText();
                    linha[1]=viatura.text_modelo.getText();
                    linha[2]=viatura.text_placa.getText();
                    linha[3]=viatura.text_ano.getText();
                    linha[4]=viatura.text_prio.getText();
                    linha[5]=viatura.text_condição.getText();
                    
                    modelo.addRow(linha);
                    viatura.text_ID.setText("");
                    viatura.text_modelo.setText("");
                    viatura.text_placa.setText("");
                    viatura.text_ano.setText("");
                    viatura.text_prio.setText("");
                    viatura.text_condição.setText("");
                    
                viatura.dispose();
                viatura.getDesktopPane().remove(viatura);
            }
            
        });
    }//GEN-LAST:event_adicionarActionPerformed

    private void lista_viaturasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lista_viaturasMouseClicked
        int index = lista_viaturas.getSelectedRow();
        TableModel modelo = lista_viaturas.getModel();
        
        if(evt.getClickCount()==2){
        
        try {
            AudioInputStream as = AudioSystem.getAudioInputStream(this.getClass().getResource("/Sounds/interfaceSFX/lista_folha.wav"));
            Clip clip = AudioSystem.getClip();
            clip.open(as);
            clip.start( );
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,"Erro");
        }
        
        String id = modelo.getValueAt(index, 0).toString();
        String modelo1 = modelo.getValueAt(index, 1).toString();
        String placa = modelo.getValueAt(index, 2).toString();
        String ano = modelo.getValueAt(index, 3).toString();
        String prio = modelo.getValueAt(index, 4).toString();
        String condição = modelo.getValueAt(index, 5).toString();
        
        Viatura viatura = Viatura.getInstance();
        getParent().add(viatura);
        viatura.Salvar.setVisible(false);
        viatura.setVisible(true);
        viatura.pack();
        
        viatura.text_ID.setText(id);
        viatura.text_modelo.setText(modelo1);
        viatura.text_placa.setText(placa);
        viatura.text_ano.setText(ano);
        viatura.text_prio.setText(prio);
        viatura.text_condição.setText(condição);
        
        centralizarJanela(viatura);
            
        }
        
    }//GEN-LAST:event_lista_viaturasMouseClicked

    private void botão_vanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botão_vanActionPerformed
        Janela_Van telavan = Janela_Van.getInstance();
        
        telavan.pack();
        
        if (telavan.isVisible()){
            
        } else {
            getParent().add(telavan);
            telavan.setVisible(true);
        }
        
        String user = Janela_Login.Campo_Nome.getText();
        String pass = new String(Janela_Login.Campo_Senha.getPassword());
        
        if(user.equals("Brian Irons") && pass.equals("2236")){
            
           Janela_Van.adicionar.setVisible(true);
           Janela_Van.editar.setVisible(true);
           Janela_Van.remover.setVisible(true);
        }else{
           Janela_Van.adicionar.setVisible(false);
           Janela_Van.editar.setVisible(false);
           Janela_Van.remover.setVisible(false); 
        }
        
        try {
            AudioInputStream as = AudioSystem.getAudioInputStream(this.getClass().getResource("/Sounds/interfaceSFX/Botão_select.wav"));
            Clip clip = AudioSystem.getClip();
            clip.open(as);
            clip.start( );
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,"Erro");
        }
        
        centralizarJanela(telavan);
        
        dispose();
        this.getDesktopPane().remove(this);
    }//GEN-LAST:event_botão_vanActionPerformed

    private void removerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removerActionPerformed
        DefaultTableModel modelo = (DefaultTableModel)lista_viaturas.getModel();
        int remove_linha = lista_viaturas.getSelectedRow();
        
        try {
            AudioInputStream as = AudioSystem.getAudioInputStream(this.getClass().getResource("/Sounds/interfaceSFX/Botão_select.wav"));
            Clip clip = AudioSystem.getClip();
            clip.open(as);
            clip.start( );
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,"Erro");
        }
        
        modelo.removeRow(remove_linha);
    }//GEN-LAST:event_removerActionPerformed

    private void editarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarActionPerformed
       int index = lista_viaturas.getSelectedRow();
        final TableModel modelo = lista_viaturas.getModel();
        
        try {
            AudioInputStream as = AudioSystem.getAudioInputStream(this.getClass().getResource("/Sounds/interfaceSFX/Botão_select.wav"));
            Clip clip = AudioSystem.getClip();
            clip.open(as);
            clip.start( );
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,"Erro");
        }
        
        String id = modelo.getValueAt(index, 0).toString();
        String modelo1 = modelo.getValueAt(index, 1).toString();
        String placa = modelo.getValueAt(index, 2).toString();
        String ano = modelo.getValueAt(index, 3).toString();
        String prio = modelo.getValueAt(index, 4).toString();
        String condição = modelo.getValueAt(index, 5).toString();
        
        final Viatura viatura = Viatura.getInstance();
        getParent().add(viatura);
        viatura.Salvar.setVisible(true);
        viatura.setVisible(true);
        viatura.pack();
        
        viatura.text_ID.setEditable(true);
        viatura.text_modelo.setEditable(true);
        viatura.text_placa.setEditable(true);
        viatura.text_ano.setEditable(true);
        viatura.text_prio.setEditable(true);
        viatura.text_condição.setEditable(true);
        
        centralizarJanela(viatura);
        
        viatura.text_ID.setText(id);
        viatura.text_modelo.setText(modelo1);
        viatura.text_placa.setText(placa);
        viatura.text_ano.setText(ano);
        viatura.text_prio.setText(prio);
        viatura.text_condição.setText(condição);
        
        viatura.Salvar.addActionListener(new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent ae) {
                
                try {
                    AudioInputStream as = AudioSystem.getAudioInputStream(this.getClass().getResource("/Sounds/interfaceSFX/Botão_select.wav"));
                    Clip clip = AudioSystem.getClip();
                    clip.open(as);
                    clip.start( );
                }
                catch(Exception e)
                {
                    JOptionPane.showMessageDialog(null,"Erro");
                }
                
                int i = lista_viaturas.getSelectedRow();
                
                modelo.setValueAt(viatura.text_ID.getText(), i, 0);
                modelo.setValueAt(viatura.text_modelo.getText(), i, 1);
                modelo.setValueAt(viatura.text_placa.getText(), i, 2);
                modelo.setValueAt(viatura.text_ano.getText(), i, 3);
                modelo.setValueAt(viatura.text_prio.getText(), i, 4);
                modelo.setValueAt(viatura.text_condição.getText(), i, 5);
                viatura.dispose();
                viatura.getDesktopPane().remove(viatura);
            }
        });
    }//GEN-LAST:event_editarActionPerformed

    private void solicitarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_solicitarActionPerformed
        int index = lista_viaturas.getSelectedRow();
        TableModel modelo = lista_viaturas.getModel();
        
        try {
            AudioInputStream as = AudioSystem.getAudioInputStream(this.getClass().getResource("/Sounds/interfaceSFX/Botão_select.wav"));
            Clip clip = AudioSystem.getClip();
            clip.open(as);
            clip.start( );
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,"Erro");
        }
        
        String id = modelo.getValueAt(index, 0).toString();
        String modelo1 = modelo.getValueAt(index, 1).toString();
        String placa = modelo.getValueAt(index, 2).toString();
        String ano = modelo.getValueAt(index, 3).toString();
        String prio = modelo.getValueAt(index, 4).toString();
        String condição = modelo.getValueAt(index, 5).toString();
        
        int i = lista_viaturas.getSelectedRow();
        
        if(condição.equals("0")){
            modelo.setValueAt("1", i, 5);
            mensagem m = mensagem.getInstance();
            getParent().add(m);
            m.toFront();
            m.setVisible(true);
            m.descrição.setForeground(new Color(51,204,0));
            m.descrição.setText("<html><b><font color='WHITE'>Solicitação de </font>Viatura<font color='WHITE'> bem sucedida !</font>");
            centralizarJanela(m);
        }else{
            mensagem m = mensagem.getInstance();
            getParent().add(m);
            m.toFront();
            m.setVisible(true);
            m.descrição.setText("<html><b><font color='red'>ERRO:</font> Veiculo em Uso");
            centralizarJanela(m);
        }
        
    }//GEN-LAST:event_solicitarActionPerformed
        

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JButton Botão_X;
    private javax.swing.JLabel Sobre;
    private javax.swing.JLabel VIATURAS;
    public static javax.swing.JButton adicionar;
    private javax.swing.JButton botão_car;
    private javax.swing.JButton botão_van;
    public static javax.swing.JButton editar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JTable lista_viaturas;
    public static javax.swing.JButton remover;
    private javax.swing.JButton solicitar;
    // End of variables declaration//GEN-END:variables
}
