/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package rpdms;

import java.awt.Color;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.util.concurrent.TimeUnit;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.sound.sampled.AudioInputStream;
import javax.sound.sampled.AudioSystem;
import javax.sound.sampled.Clip;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author 3855-1169
 */
public class Perfil extends javax.swing.JFrame {

    /**
     * Creates new form Perfil
     */
    public Perfil() {
        this.setUndecorated(true);
        this.setBackground(new Color(0,0,0,0));
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        text_nome = new javax.swing.JTextField();
        text_datanasc = new javax.swing.JTextField();
        text_sexo = new javax.swing.JTextField();
        text_raça = new javax.swing.JTextField();
        text_ts = new javax.swing.JTextField();
        text_cpf = new javax.swing.JTextField();
        text_endereço = new javax.swing.JTextField();
        text_ID = new javax.swing.JTextField();
        text_divisão = new javax.swing.JTextField();
        text_patente = new javax.swing.JTextField();
        text_assinatura = new javax.swing.JTextField();
        text_cdp = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        text_formação = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        text_especialidades = new javax.swing.JTextArea();
        Salvar = new javax.swing.JButton();
        Fechar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setOpaque(false);
        jPanel1.setLayout(null);

        text_nome.setEditable(false);
        text_nome.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        text_nome.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        text_nome.setBorder(null);
        text_nome.setOpaque(false);
        text_nome.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                text_nomeKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                text_nomeKeyTyped(evt);
            }
        });
        jPanel1.add(text_nome);
        text_nome.setBounds(180, 138, 300, 20);

        text_datanasc.setEditable(false);
        text_datanasc.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        text_datanasc.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        text_datanasc.setBorder(null);
        text_datanasc.setOpaque(false);
        text_datanasc.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                text_datanascKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                text_datanascKeyTyped(evt);
            }
        });
        jPanel1.add(text_datanasc);
        text_datanasc.setBounds(300, 175, 180, 20);

        text_sexo.setEditable(false);
        text_sexo.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        text_sexo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        text_sexo.setBorder(null);
        text_sexo.setOpaque(false);
        text_sexo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                text_sexoKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                text_sexoKeyTyped(evt);
            }
        });
        jPanel1.add(text_sexo);
        text_sexo.setBounds(180, 213, 100, 20);

        text_raça.setEditable(false);
        text_raça.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        text_raça.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        text_raça.setBorder(null);
        text_raça.setOpaque(false);
        text_raça.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                text_raçaKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                text_raçaKeyTyped(evt);
            }
        });
        jPanel1.add(text_raça);
        text_raça.setBounds(350, 213, 130, 20);

        text_ts.setEditable(false);
        text_ts.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        text_ts.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        text_ts.setBorder(null);
        text_ts.setOpaque(false);
        text_ts.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                text_tsKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                text_tsKeyTyped(evt);
            }
        });
        jPanel1.add(text_ts);
        text_ts.setBounds(270, 250, 50, 20);

        text_cpf.setEditable(false);
        text_cpf.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        text_cpf.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        text_cpf.setBorder(null);
        text_cpf.setOpaque(false);
        text_cpf.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                text_cpfKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                text_cpfKeyTyped(evt);
            }
        });
        jPanel1.add(text_cpf);
        text_cpf.setBounds(382, 250, 100, 20);

        text_endereço.setEditable(false);
        text_endereço.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        text_endereço.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        text_endereço.setBorder(null);
        text_endereço.setOpaque(false);
        text_endereço.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                text_endereçoKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                text_endereçoKeyTyped(evt);
            }
        });
        jPanel1.add(text_endereço);
        text_endereço.setBounds(220, 288, 260, 20);

        text_ID.setEditable(false);
        text_ID.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        text_ID.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        text_ID.setBorder(null);
        text_ID.setOpaque(false);
        text_ID.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                text_IDKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                text_IDKeyTyped(evt);
            }
        });
        jPanel1.add(text_ID);
        text_ID.setBounds(552, 288, 90, 20);

        text_divisão.setEditable(false);
        text_divisão.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        text_divisão.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        text_divisão.setBorder(null);
        text_divisão.setOpaque(false);
        text_divisão.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                text_divisãoKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                text_divisãoKeyTyped(evt);
            }
        });
        jPanel1.add(text_divisão);
        text_divisão.setBounds(208, 325, 90, 20);

        text_patente.setEditable(false);
        text_patente.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        text_patente.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        text_patente.setBorder(null);
        text_patente.setOpaque(false);
        text_patente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                text_patenteKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                text_patenteKeyTyped(evt);
            }
        });
        jPanel1.add(text_patente);
        text_patente.setBounds(380, 325, 100, 20);

        text_assinatura.setEditable(false);
        text_assinatura.setFont(new java.awt.Font("Rage Italic", 0, 16)); // NOI18N
        text_assinatura.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        text_assinatura.setBorder(null);
        text_assinatura.setOpaque(false);
        jPanel1.add(text_assinatura);
        text_assinatura.setBounds(190, 666, 130, 20);

        text_cdp.setEditable(false);
        text_cdp.setFont(new java.awt.Font("Rage Italic", 0, 16)); // NOI18N
        text_cdp.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        text_cdp.setText("Brian Irons");
        text_cdp.setBorder(null);
        text_cdp.setOpaque(false);
        jPanel1.add(text_cdp);
        text_cdp.setBounds(470, 666, 130, 20);

        jScrollPane1.setBorder(null);
        jScrollPane1.setOpaque(false);
        jScrollPane1.setPreferredSize(new java.awt.Dimension(164, 20));

        text_formação.setEditable(false);
        text_formação.setBackground(new java.awt.Color(226, 212, 185));
        text_formação.setColumns(20);
        text_formação.setLineWrap(true);
        text_formação.setWrapStyleWord(true);
        text_formação.setPreferredSize(new java.awt.Dimension(160, 20));
        text_formação.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                text_formaçãoKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                text_formaçãoKeyTyped(evt);
            }
        });
        jScrollPane1.setViewportView(text_formação);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(140, 408, 518, 75);

        jScrollPane2.setBorder(null);

        text_especialidades.setEditable(false);
        text_especialidades.setBackground(new java.awt.Color(226, 212, 185));
        text_especialidades.setColumns(20);
        text_especialidades.setLineWrap(true);
        text_especialidades.setRows(5);
        text_especialidades.setWrapStyleWord(true);
        text_especialidades.setBorder(null);
        text_especialidades.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                text_especialidadesKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                text_especialidadesKeyTyped(evt);
            }
        });
        jScrollPane2.setViewportView(text_especialidades);

        jPanel1.add(jScrollPane2);
        jScrollPane2.setBounds(140, 540, 520, 90);

        Salvar.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        Salvar.setText("SALVAR");
        Salvar.setBorder(null);
        Salvar.setContentAreaFilled(false);
        jPanel1.add(Salvar);
        Salvar.setBounds(186, 6, 60, 30);

        Fechar.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        Fechar.setText("FECHAR");
        Fechar.setBorder(null);
        Fechar.setContentAreaFilled(false);
        Fechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FecharActionPerformed(evt);
            }
        });
        jPanel1.add(Fechar);
        Fechar.setBounds(105, 6, 60, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/perfil_e_casos.png"))); // NOI18N
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel1MousePressed(evt);
            }
        });
        jLabel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jLabel1MouseDragged(evt);
            }
        });
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 728, 768);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 728, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 768, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
// Permite movimentar a tela 
    
    int posx,posy;
    private void jLabel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MousePressed
        posx = evt.getX();
        posy = evt.getY();
    }//GEN-LAST:event_jLabel1MousePressed

    private void jLabel1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseDragged
        this.setLocation(this.getX() + evt.getX() - posx, this.getY() + evt.getY() - posy);
    }//GEN-LAST:event_jLabel1MouseDragged

    private void FecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FecharActionPerformed
        try {
            AudioInputStream as = AudioSystem.getAudioInputStream(this.getClass().getResource("/Sounds/InterfaceSFX/Botão_sair.wav"));
            Clip clip = AudioSystem.getClip();
            clip.open(as);
            clip.start( );
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,"Erro");
        };
        
        try {
            TimeUnit.MILLISECONDS.sleep(100);
        } catch (InterruptedException ex) {
            Logger.getLogger(Janela_Sobre.class.getName()).log(Level.SEVERE, null, ex);
        }
        dispose();
        this.remove(this);
    }//GEN-LAST:event_FecharActionPerformed

    private void text_nomeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_text_nomeKeyTyped
        if(evt.getKeyChar() == KeyEvent.VK_BACK_SPACE){
            try {
                AudioInputStream as = AudioSystem.getAudioInputStream(this.getClass().getResource("/Sounds/interfaceSFX/Digito_backspace.wav"));
                Clip clip = AudioSystem.getClip();
                clip.open(as);
                clip.start( );
            }
            catch(Exception e)
            {
                JOptionPane.showMessageDialog(null,"Erro");
            }
        }else{
            try {
                AudioInputStream as = AudioSystem.getAudioInputStream(this.getClass().getResource("/Sounds/interfaceSFX/Digito.wav"));
                Clip clip = AudioSystem.getClip();
                clip.open(as);
                clip.start( );
            }
            catch(Exception e)
            {
                JOptionPane.showMessageDialog(null,"Erro");
            }
        }
    }//GEN-LAST:event_text_nomeKeyTyped

    private void text_datanascKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_text_datanascKeyTyped
        if(evt.getKeyChar() == KeyEvent.VK_BACK_SPACE){
            try {
                AudioInputStream as = AudioSystem.getAudioInputStream(this.getClass().getResource("/Sounds/interfaceSFX/Digito_backspace.wav"));
                Clip clip = AudioSystem.getClip();
                clip.open(as);
                clip.start( );
            }
            catch(Exception e)
            {
                JOptionPane.showMessageDialog(null,"Erro");
            }
        }else{
            try {
                AudioInputStream as = AudioSystem.getAudioInputStream(this.getClass().getResource("/Sounds/interfaceSFX/Digito.wav"));
                Clip clip = AudioSystem.getClip();
                clip.open(as);
                clip.start( );
            }
            catch(Exception e)
            {
                JOptionPane.showMessageDialog(null,"Erro");
            }
        }
    }//GEN-LAST:event_text_datanascKeyTyped

    private void text_sexoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_text_sexoKeyTyped
        if(evt.getKeyChar() == KeyEvent.VK_BACK_SPACE){
            try {
                AudioInputStream as = AudioSystem.getAudioInputStream(this.getClass().getResource("/Sounds/interfaceSFX/Digito_backspace.wav"));
                Clip clip = AudioSystem.getClip();
                clip.open(as);
                clip.start( );
            }
            catch(Exception e)
            {
                JOptionPane.showMessageDialog(null,"Erro");
            }
        }else{
            try {
                AudioInputStream as = AudioSystem.getAudioInputStream(this.getClass().getResource("/Sounds/interfaceSFX/Digito.wav"));
                Clip clip = AudioSystem.getClip();
                clip.open(as);
                clip.start( );
            }
            catch(Exception e)
            {
                JOptionPane.showMessageDialog(null,"Erro");
            }
        }
    }//GEN-LAST:event_text_sexoKeyTyped

    private void text_raçaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_text_raçaKeyTyped
        if(evt.getKeyChar() == KeyEvent.VK_BACK_SPACE){
            try {
                AudioInputStream as = AudioSystem.getAudioInputStream(this.getClass().getResource("/Sounds/interfaceSFX/Digito_backspace.wav"));
                Clip clip = AudioSystem.getClip();
                clip.open(as);
                clip.start( );
            }
            catch(Exception e)
            {
                JOptionPane.showMessageDialog(null,"Erro");
            }
        }else{
            try {
                AudioInputStream as = AudioSystem.getAudioInputStream(this.getClass().getResource("/Sounds/interfaceSFX/Digito.wav"));
                Clip clip = AudioSystem.getClip();
                clip.open(as);
                clip.start( );
            }
            catch(Exception e)
            {
                JOptionPane.showMessageDialog(null,"Erro");
            }
        }
    }//GEN-LAST:event_text_raçaKeyTyped

    private void text_tsKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_text_tsKeyTyped
        if(evt.getKeyChar() == KeyEvent.VK_BACK_SPACE){
            try {
                AudioInputStream as = AudioSystem.getAudioInputStream(this.getClass().getResource("/Sounds/interfaceSFX/Digito_backspace.wav"));
                Clip clip = AudioSystem.getClip();
                clip.open(as);
                clip.start( );
            }
            catch(Exception e)
            {
                JOptionPane.showMessageDialog(null,"Erro");
            }
        }else{
            try {
                AudioInputStream as = AudioSystem.getAudioInputStream(this.getClass().getResource("/Sounds/interfaceSFX/Digito.wav"));
                Clip clip = AudioSystem.getClip();
                clip.open(as);
                clip.start( );
            }
            catch(Exception e)
            {
                JOptionPane.showMessageDialog(null,"Erro");
            }
        }
    }//GEN-LAST:event_text_tsKeyTyped

    private void text_cpfKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_text_cpfKeyTyped
        if(evt.getKeyChar() == KeyEvent.VK_BACK_SPACE){
            try {
                AudioInputStream as = AudioSystem.getAudioInputStream(this.getClass().getResource("/Sounds/interfaceSFX/Digito_backspace.wav"));
                Clip clip = AudioSystem.getClip();
                clip.open(as);
                clip.start( );
            }
            catch(Exception e)
            {
                JOptionPane.showMessageDialog(null,"Erro");
            }
        }else{
            try {
                AudioInputStream as = AudioSystem.getAudioInputStream(this.getClass().getResource("/Sounds/interfaceSFX/Digito.wav"));
                Clip clip = AudioSystem.getClip();
                clip.open(as);
                clip.start( );
            }
            catch(Exception e)
            {
                JOptionPane.showMessageDialog(null,"Erro");
            }
        }
    }//GEN-LAST:event_text_cpfKeyTyped

    private void text_endereçoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_text_endereçoKeyTyped
        if(evt.getKeyChar() == KeyEvent.VK_BACK_SPACE){
            try {
                AudioInputStream as = AudioSystem.getAudioInputStream(this.getClass().getResource("/Sounds/interfaceSFX/Digito_backspace.wav"));
                Clip clip = AudioSystem.getClip();
                clip.open(as);
                clip.start( );
            }
            catch(Exception e)
            {
                JOptionPane.showMessageDialog(null,"Erro");
            }
        }else{
            try {
                AudioInputStream as = AudioSystem.getAudioInputStream(this.getClass().getResource("/Sounds/interfaceSFX/Digito.wav"));
                Clip clip = AudioSystem.getClip();
                clip.open(as);
                clip.start( );
            }
            catch(Exception e)
            {
                JOptionPane.showMessageDialog(null,"Erro");
            }
        }
    }//GEN-LAST:event_text_endereçoKeyTyped

    private void text_IDKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_text_IDKeyTyped
        if(evt.getKeyChar() == KeyEvent.VK_BACK_SPACE){
            try {
                AudioInputStream as = AudioSystem.getAudioInputStream(this.getClass().getResource("/Sounds/interfaceSFX/Digito_backspace.wav"));
                Clip clip = AudioSystem.getClip();
                clip.open(as);
                clip.start( );
            }
            catch(Exception e)
            {
                JOptionPane.showMessageDialog(null,"Erro");
            }
        }else{
            try {
                AudioInputStream as = AudioSystem.getAudioInputStream(this.getClass().getResource("/Sounds/interfaceSFX/Digito.wav"));
                Clip clip = AudioSystem.getClip();
                clip.open(as);
                clip.start( );
            }
            catch(Exception e)
            {
                JOptionPane.showMessageDialog(null,"Erro");
            }
        }
    }//GEN-LAST:event_text_IDKeyTyped

    private void text_divisãoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_text_divisãoKeyTyped
        if(evt.getKeyChar() == KeyEvent.VK_BACK_SPACE){
            try {
                AudioInputStream as = AudioSystem.getAudioInputStream(this.getClass().getResource("/Sounds/interfaceSFX/Digito_backspace.wav"));
                Clip clip = AudioSystem.getClip();
                clip.open(as);
                clip.start( );
            }
            catch(Exception e)
            {
                JOptionPane.showMessageDialog(null,"Erro");
            }
        }else{
            try {
                AudioInputStream as = AudioSystem.getAudioInputStream(this.getClass().getResource("/Sounds/interfaceSFX/Digito.wav"));
                Clip clip = AudioSystem.getClip();
                clip.open(as);
                clip.start( );
            }
            catch(Exception e)
            {
                JOptionPane.showMessageDialog(null,"Erro");
            }
        }
    }//GEN-LAST:event_text_divisãoKeyTyped

    private void text_patenteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_text_patenteKeyTyped
        if(evt.getKeyChar() == KeyEvent.VK_BACK_SPACE){
            try {
                AudioInputStream as = AudioSystem.getAudioInputStream(this.getClass().getResource("/Sounds/interfaceSFX/Digito_backspace.wav"));
                Clip clip = AudioSystem.getClip();
                clip.open(as);
                clip.start( );
            }
            catch(Exception e)
            {
                JOptionPane.showMessageDialog(null,"Erro");
            }
        }else{
            try {
                AudioInputStream as = AudioSystem.getAudioInputStream(this.getClass().getResource("/Sounds/interfaceSFX/Digito.wav"));
                Clip clip = AudioSystem.getClip();
                clip.open(as);
                clip.start( );
            }
            catch(Exception e)
            {
                JOptionPane.showMessageDialog(null,"Erro");
            }
        }
    }//GEN-LAST:event_text_patenteKeyTyped

    private void text_formaçãoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_text_formaçãoKeyTyped
        if(evt.getKeyChar() == KeyEvent.VK_BACK_SPACE){
            try {
                AudioInputStream as = AudioSystem.getAudioInputStream(this.getClass().getResource("/Sounds/interfaceSFX/Digito_backspace.wav"));
                Clip clip = AudioSystem.getClip();
                clip.open(as);
                clip.start( );
            }
            catch(Exception e)
            {
                JOptionPane.showMessageDialog(null,"Erro");
            }
        }else{
            try {
                AudioInputStream as = AudioSystem.getAudioInputStream(this.getClass().getResource("/Sounds/interfaceSFX/Digito.wav"));
                Clip clip = AudioSystem.getClip();
                clip.open(as);
                clip.start( );
            }
            catch(Exception e)
            {
                JOptionPane.showMessageDialog(null,"Erro");
            }
        }
    }//GEN-LAST:event_text_formaçãoKeyTyped

    private void text_especialidadesKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_text_especialidadesKeyTyped
        if(evt.getKeyChar() == KeyEvent.VK_BACK_SPACE){
            try {
                AudioInputStream as = AudioSystem.getAudioInputStream(this.getClass().getResource("/Sounds/interfaceSFX/Digito_backspace.wav"));
                Clip clip = AudioSystem.getClip();
                clip.open(as);
                clip.start( );
            }
            catch(Exception e)
            {
                JOptionPane.showMessageDialog(null,"Erro");
            }
        }else{
            try {
                AudioInputStream as = AudioSystem.getAudioInputStream(this.getClass().getResource("/Sounds/interfaceSFX/Digito.wav"));
                Clip clip = AudioSystem.getClip();
                clip.open(as);
                clip.start( );
            }
            catch(Exception e)
            {
                JOptionPane.showMessageDialog(null,"Erro");
            }
        }
    }//GEN-LAST:event_text_especialidadesKeyTyped

    private void text_nomeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_text_nomeKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_SPACE){
            try {
                AudioInputStream as = AudioSystem.getAudioInputStream(this.getClass().getResource("/Sounds/interfaceSFX/Digito_espaço.wav"));
                Clip clip = AudioSystem.getClip();
                clip.open(as);
                clip.start( );
            }
            catch (Exception e) {
                JOptionPane.showMessageDialog(null,"Erro");
            }

        }
    }//GEN-LAST:event_text_nomeKeyPressed

    private void text_datanascKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_text_datanascKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_SPACE){
            try {
                AudioInputStream as = AudioSystem.getAudioInputStream(this.getClass().getResource("/Sounds/interfaceSFX/Digito_espaço.wav"));
                Clip clip = AudioSystem.getClip();
                clip.open(as);
                clip.start( );
            }
            catch (Exception e) {
                JOptionPane.showMessageDialog(null,"Erro");
            }

        }
    }//GEN-LAST:event_text_datanascKeyPressed

    private void text_sexoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_text_sexoKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_SPACE){
            try {
                AudioInputStream as = AudioSystem.getAudioInputStream(this.getClass().getResource("/Sounds/interfaceSFX/Digito_espaço.wav"));
                Clip clip = AudioSystem.getClip();
                clip.open(as);
                clip.start( );
            }
            catch (Exception e) {
                JOptionPane.showMessageDialog(null,"Erro");
            }

        }
    }//GEN-LAST:event_text_sexoKeyPressed

    private void text_raçaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_text_raçaKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_SPACE){
            try {
                AudioInputStream as = AudioSystem.getAudioInputStream(this.getClass().getResource("/Sounds/interfaceSFX/Digito_espaço.wav"));
                Clip clip = AudioSystem.getClip();
                clip.open(as);
                clip.start( );
            }
            catch (Exception e) {
                JOptionPane.showMessageDialog(null,"Erro");
            }

        }
    }//GEN-LAST:event_text_raçaKeyPressed

    private void text_tsKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_text_tsKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_SPACE){
            try {
                AudioInputStream as = AudioSystem.getAudioInputStream(this.getClass().getResource("/Sounds/interfaceSFX/Digito_espaço.wav"));
                Clip clip = AudioSystem.getClip();
                clip.open(as);
                clip.start( );
            }
            catch (Exception e) {
                JOptionPane.showMessageDialog(null,"Erro");
            }

        }
    }//GEN-LAST:event_text_tsKeyPressed

    private void text_cpfKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_text_cpfKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_SPACE){
            try {
                AudioInputStream as = AudioSystem.getAudioInputStream(this.getClass().getResource("/Sounds/interfaceSFX/Digito_espaço.wav"));
                Clip clip = AudioSystem.getClip();
                clip.open(as);
                clip.start( );
            }
            catch (Exception e) {
                JOptionPane.showMessageDialog(null,"Erro");
            }

        }
    }//GEN-LAST:event_text_cpfKeyPressed

    private void text_endereçoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_text_endereçoKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_SPACE){
            try {
                AudioInputStream as = AudioSystem.getAudioInputStream(this.getClass().getResource("/Sounds/interfaceSFX/Digito_espaço.wav"));
                Clip clip = AudioSystem.getClip();
                clip.open(as);
                clip.start( );
            }
            catch (Exception e) {
                JOptionPane.showMessageDialog(null,"Erro");
            }

        }
    }//GEN-LAST:event_text_endereçoKeyPressed

    private void text_IDKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_text_IDKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_SPACE){
            try {
                AudioInputStream as = AudioSystem.getAudioInputStream(this.getClass().getResource("/Sounds/interfaceSFX/Digito_espaço.wav"));
                Clip clip = AudioSystem.getClip();
                clip.open(as);
                clip.start( );
            }
            catch (Exception e) {
                JOptionPane.showMessageDialog(null,"Erro");
            }

        }
    }//GEN-LAST:event_text_IDKeyPressed

    private void text_divisãoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_text_divisãoKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_SPACE){
            try {
                AudioInputStream as = AudioSystem.getAudioInputStream(this.getClass().getResource("/Sounds/interfaceSFX/Digito_espaço.wav"));
                Clip clip = AudioSystem.getClip();
                clip.open(as);
                clip.start( );
            }
            catch (Exception e) {
                JOptionPane.showMessageDialog(null,"Erro");
            }

        }
    }//GEN-LAST:event_text_divisãoKeyPressed

    private void text_patenteKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_text_patenteKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_SPACE){
            try {
                AudioInputStream as = AudioSystem.getAudioInputStream(this.getClass().getResource("/Sounds/interfaceSFX/Digito_espaço.wav"));
                Clip clip = AudioSystem.getClip();
                clip.open(as);
                clip.start( );
            }
            catch (Exception e) {
                JOptionPane.showMessageDialog(null,"Erro");
            }

        }
    }//GEN-LAST:event_text_patenteKeyPressed

    private void text_formaçãoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_text_formaçãoKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_SPACE){
            try {
                AudioInputStream as = AudioSystem.getAudioInputStream(this.getClass().getResource("/Sounds/interfaceSFX/Digito_espaço.wav"));
                Clip clip = AudioSystem.getClip();
                clip.open(as);
                clip.start( );
            }
            catch (Exception e) {
                JOptionPane.showMessageDialog(null,"Erro");
            }

        }
    }//GEN-LAST:event_text_formaçãoKeyPressed

    private void text_especialidadesKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_text_especialidadesKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_SPACE){
            try {
                AudioInputStream as = AudioSystem.getAudioInputStream(this.getClass().getResource("/Sounds/interfaceSFX/Digito_espaço.wav"));
                Clip clip = AudioSystem.getClip();
                clip.open(as);
                clip.start( );
            }
            catch (Exception e) {
                JOptionPane.showMessageDialog(null,"Erro");
            }

        }
    }//GEN-LAST:event_text_especialidadesKeyPressed

    //Função pra Tornar todos os campos editáveis
    public void setEditavel (){
        text_ID.setEditable(true);
        text_cpf.setEditable(true);
        text_datanasc.setEditable(true);
        text_divisão.setEditable(true);
        text_endereço.setEditable(true);
        text_especialidades.setEditable(true);
        text_formação.setEditable(true);
        text_nome.setEditable(true);
        text_patente.setEditable(true);
        text_raça.setEditable(true);
        text_sexo.setEditable(true);
        text_ts.setEditable(true);
        text_assinatura.setEditable(true);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Perfil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Perfil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Perfil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Perfil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Perfil().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Fechar;
    public javax.swing.JButton Salvar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    public javax.swing.JTextField text_ID;
    public javax.swing.JTextField text_assinatura;
    private javax.swing.JTextField text_cdp;
    public javax.swing.JTextField text_cpf;
    public javax.swing.JTextField text_datanasc;
    public javax.swing.JTextField text_divisão;
    public javax.swing.JTextField text_endereço;
    public javax.swing.JTextArea text_especialidades;
    public javax.swing.JTextArea text_formação;
    public javax.swing.JTextField text_nome;
    public javax.swing.JTextField text_patente;
    public javax.swing.JTextField text_raça;
    public javax.swing.JTextField text_sexo;
    public javax.swing.JTextField text_ts;
    // End of variables declaration//GEN-END:variables
}
