/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package rpdms;

import java.awt.Color;
import java.awt.Font;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.font.TextLayout;
import javax.swing.BorderFactory;
import javax.swing.plaf.basic.BasicInternalFrameUI;

/**
 *
 * @author 3855-1169
 */
public class Relatorio extends javax.swing.JInternalFrame {

    /**
     * Creates new form Relatorio_test
     */
    public Relatorio() {
        BasicInternalFrameUI bi = (BasicInternalFrameUI)this.getUI();
        bi.setNorthPane(null);
        initComponents();
        
        scroll.getViewport().setOpaque(false);
    }
    
    private static Relatorio myInstance;// Abre uma mesma janela por vez
    
    public static Relatorio getInstance() {
        if (myInstance == null) {
        myInstance = new Relatorio();
    }else{
            myInstance.dispose();
            myInstance = new Relatorio();
        }
    return myInstance;
   }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        anterior = new javax.swing.JButton();
        scroll = new javax.swing.JScrollPane();
        texto = new javax.swing.JTextArea();
        proximo = new javax.swing.JButton();
        icon = new javax.swing.JLabel();
        background = new javax.swing.JLabel();

        setBackground(new java.awt.Color(165, 165, 157));
        setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(210, 210, 210), new java.awt.Color(210, 210, 210), null, null));

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(68, 67, 63), new java.awt.Color(68, 67, 63), new java.awt.Color(210, 210, 210), new java.awt.Color(210, 210, 210)));
        jPanel1.setPreferredSize(new java.awt.Dimension(611, 426));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        anterior.setBorder(null);
        anterior.setContentAreaFilled(false);
        anterior.setFocusPainted(false);
        anterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                anteriorActionPerformed(evt);
            }
        });
        jPanel1.add(anterior, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 182, 59, 59));

        scroll.setBorder(null);
        scroll.setForeground(new java.awt.Color(210, 210, 210));
        scroll.setOpaque(false);
        scroll.setPreferredSize(new java.awt.Dimension(440, 312));

        texto.setEditable(false);
        texto.setFont(new java.awt.Font("Courier New", 0, 24)); // NOI18N
        texto.setForeground(new java.awt.Color(240, 240, 240));
        texto.setLineWrap(true);
        texto.setRows(1);
        texto.setWrapStyleWord(true);
        texto.setBorder(null);
        texto.setOpaque(false);
        scroll.setViewportView(texto);

        jPanel1.add(scroll, new org.netbeans.lib.awtextra.AbsoluteConstraints(85, 57, 440, -1));

        proximo.setFont(new java.awt.Font("RE3", 0, 36)); // NOI18N
        proximo.setForeground(new java.awt.Color(210, 210, 210));
        proximo.setAlignmentY(0.0F);
        proximo.setBorder(null);
        proximo.setContentAreaFilled(false);
        proximo.setFocusPainted(false);
        proximo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        proximo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                proximoActionPerformed(evt);
            }
        });
        jPanel1.add(proximo, new org.netbeans.lib.awtextra.AbsoluteConstraints(531, 182, 59, 59));

        icon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/icons/icons_relatorios/file1.png"))); // NOI18N
        icon.setPreferredSize(new java.awt.Dimension(440, 310));
        jPanel1.add(icon, new org.netbeans.lib.awtextra.AbsoluteConstraints(86, 58, 440, 310));

        background.setPreferredSize(new java.awt.Dimension(611, 426));
        jPanel1.add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 611, 426));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
int cont=0;
String p = "0 - Start";
String p1 = "1 - Test";
String p2 = "2 - New";
String p3 = "3 - End";

    private void proximoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_proximoActionPerformed
        /*switch(cont){
                case 0:
                    texto.setText(p1);
                    cont++;
                    break;
                case 1:
                    texto.setText(p2);
                    cont++;
                    break;
                    
                case 2:
                    texto.setText(p3);
                    cont++;
                    break;
                    
                case 3:
                    texto.setText(p);
                    cont=0;
                    dispose();
                    this.getDesktopPane().remove(this);
                    break;
            }*/
    }//GEN-LAST:event_proximoActionPerformed

    private void anteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_anteriorActionPerformed
          /*switch(cont){
                case 3:
                    texto.setText(p2);
                    cont--;
                    break;
                case 2:
                    texto.setText(p1);
                    cont--;
                    break;
                case 1:
                    texto.setText(p);
                    cont=0;
                    break;
            }*/
    }//GEN-LAST:event_anteriorActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton anterior;
    public javax.swing.JLabel background;
    public javax.swing.JLabel icon;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JButton proximo;
    private javax.swing.JScrollPane scroll;
    public javax.swing.JTextArea texto;
    // End of variables declaration//GEN-END:variables
}
